/**
 * Purpose: Generate PDF documents for applications using pdfkit
 * Why important: Provides reliable server-side PDF generation with logo and QR code support
 * Used by: ApplicationPdfController
 */
import { Injectable, NotFoundException } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import QRCode from 'qrcode';

import { PrismaService } from '../../database/prisma.service';
import { S3Service } from '../document/s3.service';

@Injectable()
export class ApplicationPdfService {
	constructor(
		private readonly prisma: PrismaService,
		private readonly s3Service: S3Service,
	) {}

	async generateApplicationPdf(countyId: string, applicationId: string): Promise<Buffer> {
		const application = await this.prisma.application.findUnique({
			where: { id: applicationId },
		});

		if (!application) {
			throw new NotFoundException('Application not found');
		}

		const program = await this.prisma.bursaryProgram.findUnique({
			where: { id: application.programId },
		});

		if (!program) {
			throw new NotFoundException('Program not found');
		}

		const county = await this.prisma.county.findUnique({
			where: { id: countyId },
			select: {
				name: true,
				fundName: true,
				logoS3Key: true,
				primaryColor: true,
			},
		});

		if (!county) {
			throw new NotFoundException('County not found');
		}

		// Fetch logo as buffer
		let logoBuffer: Buffer | null = null;
		if (county.logoS3Key) {
			try {
				const signed = await this.s3Service.getSignedDownloadUrl(county.logoS3Key);
				const response = await fetch(signed.url);
				if (response.ok) {
					logoBuffer = Buffer.from(await response.arrayBuffer());
				}
			} catch {
				// Logo fetch failed, continue without it
			}
		}

		// Generate QR code
		const reference = application.submissionReference || application.id;
		const qrCodeDataUrl = await QRCode.toDataURL(`REF:${reference}`, {
			width: 120,
			margin: 1,
			type: 'image/png',
		});
		const qrCodeBuffer = Buffer.from(qrCodeDataUrl.split(',')[1], 'base64');

		// Create PDF
		const doc = new PDFDocument({
			size: 'A4',
			margins: { top: 50, bottom: 50, left: 50, right: 50 },
		});

		const chunks: Buffer[] = [];
		doc.on('data', (chunk) => chunks.push(chunk));

		// Header with logo
		if (logoBuffer) {
			doc.image(logoBuffer, 50, 50, { width: 60, height: 60 });
		}

		doc.fontSize(20).fillColor(county.primaryColor || '#1E3A5F');
		doc.text(`${county.name} - ${county.fundName || 'Education Fund'}`, {
			align: 'center',
		});

		doc.fontSize(12).fillColor('#333');
		doc.text('Bursary Application Form', { align: 'center' });
		doc.moveDown();

		// Application details
		doc.fontSize(10).fillColor('#666');
		doc.text(`Program: ${program.name}`);
		doc.text(`Reference: ${reference}`);
		doc.text(`Generated: ${new Date().toLocaleDateString()}`);
		doc.moveDown();

		// Draw line
		doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
		doc.moveDown();

		// Section B: Financial Information
		this.addSection(doc, 'Section B: Financial Information', [
			{ label: 'Total Fee (KES)', value: application.totalFeeKes?.toString() || 'N/A' },
			{ label: 'Outstanding Balance (KES)', value: application.outstandingBalance?.toString() || 'N/A' },
			{ label: 'Amount Requested (KES)', value: application.amountRequested?.toString() || 'N/A' },
			{ label: 'HELB Applied', value: application.helbApplied ? 'Yes' : 'No' },
		]);

		// Add QR code at bottom
		if (doc.y > 650) {
			doc.addPage();
		}
		doc.image(qrCodeBuffer, 50, doc.y, { width: 80, height: 80 });
		doc.fontSize(9).fillColor('#666');
		doc.text(`Unique Serial No: ${reference}`, 140, doc.y - 70);
		doc.text('Scan to verify authenticity', 140, doc.y - 55);

		// Footer
		doc.fontSize(8).fillColor('#999');
		doc.text('Generated by KauntyBursary student portal. Keep this copy for your records.', {
			align: 'center',
		});

		doc.end();

		return new Promise((resolve, reject) => {
			doc.on('end', () => resolve(Buffer.concat(chunks)));
			doc.on('error', reject);
		});
	}

	private addSection(doc: any, title: string, fields: { label: string; value: string }[]) {
		if (doc.y > 650) {
			doc.addPage();
		}

		doc.fontSize(12).fillColor('#1E3A5F').text(title);
		doc.moveDown(0.5);

		doc.fontSize(10).fillColor('#333');
		fields.forEach((field) => {
			doc.fillColor('#666').text(`${field.label}:`, { continued: true });
			doc.fillColor('#333').text(` ${field.value}`);
		});

		doc.moveDown();
	}
}
