import { Document, Page, StyleSheet, Text, View, renderToBuffer } from "@react-pdf/renderer";

import { formatShortDate } from "@/lib/format";
import type { PreviewSection } from "@/lib/application-preview";

type ApplicationPdfParams = {
	countyName: string;
	fundName: string;
	primaryColor: string;
	legalReference: string;
	programName: string;
	reference: string;
	generatedAt: string;
	sections: PreviewSection[];
};

const styles = StyleSheet.create({
	page: {
		paddingTop: 28,
		paddingRight: 30,
		paddingBottom: 28,
		paddingLeft: 30,
		fontSize: 10,
		fontFamily: "Helvetica",
		color: "#111827",
	},
	header: {
		borderWidth: 1,
		borderColor: "#0d2b4e",
		borderRadius: 6,
		padding: 10,
	},
	headerCaption: {
		fontSize: 9,
		color: "#1e3a5f",
		textTransform: "uppercase",
	},
	headerTitle: {
		marginTop: 4,
		fontSize: 14,
		fontWeight: 700,
		color: "#0d2b4e",
	},
	metaRow: {
		marginTop: 6,
		gap: 3,
	},
	metaText: {
		fontSize: 9,
		color: "#4b5563",
	},
	section: {
		marginTop: 10,
		borderWidth: 1,
		borderColor: "#d1d5db",
		borderRadius: 6,
		overflow: "hidden",
	},
	sectionTitle: {
		fontSize: 10,
		fontWeight: 700,
		backgroundColor: "#eff6fc",
		color: "#0d2b4e",
		paddingTop: 7,
		paddingRight: 8,
		paddingBottom: 7,
		paddingLeft: 8,
	},
	row: {
		flexDirection: "row",
		borderTopWidth: 1,
		borderTopColor: "#e5e7eb",
	},
	labelCell: {
		width: "36%",
		paddingTop: 6,
		paddingRight: 8,
		paddingBottom: 6,
		paddingLeft: 8,
		fontWeight: 700,
		backgroundColor: "#f9fafb",
		color: "#374151",
	},
	valueCell: {
		width: "64%",
		paddingTop: 6,
		paddingRight: 8,
		paddingBottom: 6,
		paddingLeft: 8,
		color: "#111827",
	},
	footer: {
		marginTop: 10,
		fontSize: 8,
		color: "#6b7280",
	},
});

function toRgba(hexColor: string, alpha: number): string {
	const normalized = hexColor.replace("#", "");
	if (normalized.length !== 6) {
		return `rgba(13, 43, 78, ${alpha})`;
	}

	const r = Number.parseInt(normalized.slice(0, 2), 16);
	const g = Number.parseInt(normalized.slice(2, 4), 16);
	const b = Number.parseInt(normalized.slice(4, 6), 16);
	return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

function ApplicationPdfDocument(params: ApplicationPdfParams) {
	const accentColor = params.primaryColor || "#0D2B4E";
	const sectionBackground = toRgba(accentColor, 0.1);

	return (
		<Document>
			<Page size="A4" style={styles.page}>
				<View style={[styles.header, { borderColor: accentColor }]}> 
					<Text style={[styles.headerCaption, { color: accentColor }]}>County Government Bursary Form</Text>
					<Text style={[styles.headerTitle, { color: accentColor }]}> 
						{params.countyName} - {params.fundName}
					</Text>
					<View style={styles.metaRow}>
						<Text style={styles.metaText}>Program: {params.programName}</Text>
						<Text style={styles.metaText}>Reference: {params.reference}</Text>
						<Text style={styles.metaText}>Legal Ref: {params.legalReference || "-"}</Text>
						<Text style={styles.metaText}>Generated: {formatShortDate(params.generatedAt)}</Text>
					</View>
				</View>

				{params.sections.map((section) => (
					<View key={section.slug} style={styles.section}>
						<Text style={[styles.sectionTitle, { backgroundColor: sectionBackground, color: accentColor }]}> 
							{section.title}
						</Text>
						{section.entries.length > 0 ? (
							section.entries.map((entry) => (
								<View key={`${section.slug}-${entry.label}`} style={styles.row}>
									<Text style={styles.labelCell}>{entry.label}</Text>
									<Text style={styles.valueCell}>{entry.value}</Text>
								</View>
							))
						) : (
							<View style={styles.row}>
								<Text style={styles.valueCell}>No data captured</Text>
							</View>
						)}
					</View>
				))}

				<Text style={styles.footer}>
					Generated by KauntyBursary student portal. Keep this copy for your records.
				</Text>
			</Page>
		</Document>
	);
}

export async function renderApplicationPdf(
	params: ApplicationPdfParams,
): Promise<Uint8Array<ArrayBuffer>> {
	const buffer = await renderToBuffer(<ApplicationPdfDocument {...params} />);
	const bytes = new Uint8Array(new ArrayBuffer(buffer.byteLength));
	bytes.set(buffer);
	return bytes;
}